# Introdução à Programação(BIA)
## Igor Jesus da Silva
### Matrícula: 202603053
#### E-mail institucional: igorjesus@discente.ufg.br

In [ ]:
!pip  install pandas
import pandas as pd

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
df_populacao = pd.read_csv("/content/populacao_imc.csv")
display(df_populacao)
display(df_populacao.info())

        id         nome data_nascimento sexo  peso_kg  altura_m
0        1  pessoa_1502      2000-12-06    F     85.4      1.63
1        2  pessoa_2587      1992-10-23    F     62.5      1.64
2        3  pessoa_2654      2009-06-16    M     60.0      1.64
3        4  pessoa_1056      1974-05-30    M     69.6      1.73
4        5   pessoa_706      2017-09-20    F     25.8      1.26
...    ...          ...             ...  ...      ...       ...
4995  4996  pessoa_4427      1962-05-21    M     95.0      1.68
4996  4997   pessoa_467      2016-05-14    F     34.0      1.30
4997  4998  pessoa_3093      2014-02-08    F     63.2      1.49
4998  4999  pessoa_3773      2011-07-03    M     45.4      1.51
4999  5000   pessoa_861      2019-06-06    M     19.2      1.10

[5000 rows x 6 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               5000 non-null   int64
 1   nome             5000 non-null   object
 2   data_nascimento  5000 non-null   object
 3   sexo             5000 non-null   object
 4   peso_kg          5000 non-null   float64
 5   altura_m         5000 non-null   float64
dtypes: float64(2), int64(1), object(3)
memory usage: 234.5+ KB

None

In [ ]:
#a)CALCULAR O IMC DE CADA INDIVÍDUO

#criando cópia do data frame
df_analise = df_populacao
#criar coluna de IMC e limitar a duas casas decimais
df_analise['IMC']= df_analise['peso_kg'] / (df_analise['altura_m']**2)
df_analise['IMC'] = df_analise['IMC'].round(2)

#b)atribuir a classificação correspondente considerando a faixa etária

#calcular a idade para poder classificar
from datetime import datetime# importar o tempo
df_analise['data_nascimento'] = pd.to_datetime(df_analise["data_nascimento"], format="%Y-%m-%d")#converter "data_nascimento" para "datetime"
df_analise['Idade'] = df_analise['atual'] = datetime.now().year - df_analise['data_nascimento'].dt.year#calculando idade por meio da subtração entre ano atual e ano de nacimento(dt.year = apenas "ano")
df_analise = df_analise.drop(columns=['atual']) #ocultar coluna "atual"

#classificar faixa etária

#criando uma função que retorna a faixa etária do individuo com base na sua idade
def classificar_idade(idade):
  if idade < 12:
    return 'criança'
  elif  12 <= idade < 17:
    return 'adolescente'
  elif 18 <= idade <= 59:
    return 'adulto'
  else:
    return 'idoso'

df_analise['faixa etária'] = df_analise['Idade'].apply(classificar_idade)# a classificação da faixa etária será cada valor da coluna "idade" aplicado à função

#classificar IMC

def classificar_imc(IMC):
  if IMC <= 18.5:
    return 'baixo peso'
  elif  18.5 < IMC <= 24.9:
    return 'peso normal'
  elif 25 <= IMC <= 29.9:
    return 'sobre peso'
  elif 30 <= IMC <= 34.9:
    return 'obesidade grau I'
  elif 35 <= IMC <= 39.9:
    return 'obesidade grau II'
  elif 40 <= IMC:
    return 'obesidade grau III'

df_analise['classificação'] = df_analise['IMC'].apply(classificar_imc)

print('Esse é o data frame tratado')
#Ordenar por idade
df_analise = df_analise.sort_values(by='data_nascimento')
display(df_analise)

#c) análise dos dados

print('(i)contagem e o percentual de indivíduos por classificação de IMC dentro de cada faixa etária')

# criando uma "combinação" entre duas colunas(faixa etária e classificação) e chamndo de quantidade
df_i = df_analise.groupby(["faixa etária", "classificação"]).size().reset_index(name= 'quantidade')
#com base na quantidade, calculamos o percentual... exemplo:"adolescente com baixo peso/ soma de todos 'adolescentes'"
df_i['percentual'] = (df_i['quantidade'] / df_i.groupby('faixa etária')['quantidade'].transform(sum)) * 100
#limite de duas casa decimais
df_i['percentual'] = df_i['percentual'].round(2)
display(df_i)

print('(ii) o IMC médio, mediano e o desvio-padrão por faixa etária e sexo')

#calcular a média, mediana e desvio do IMC por faixa etária e sexo
df_ii = df_analise.groupby(['faixa etária','sexo'])['IMC'].agg( media_IMC= 'mean', mediana_IMC='median' , desvio_IMC='std').round(2).reset_index()
display(df_ii)

print('uma tabela que destaque os grupos (faixa etária × sexo) com maior proporção de classificações de risco')

#classificar quais grupos são de risco
risco = ['baixo peso', 'sobre peso', 'obesidade grau I', 'obesidade grau II', 'obesidade grau III']
#verificar se cada valor da coluna classificação está na lista risco
df_iii = df_analise['risco'] = df_analise['classificação'].isin(risco)
#calcular média atrelado à faixa etária e sexo e atribuir o nome de "percentual de  risco". Ordenar de forma decrescente
df_iii = df_analise.groupby(['faixa etária','sexo'])['risco'].mean().reset_index(name='percentual de risco').sort_values(by='percentual de risco', ascending=False)
#limitar a duas casas decimais e multiplicar por 100
df_iii['percentual de risco'] = df_iii['percentual de risco'].round(2) * 100
display(df_iii)

Esse é o data frame tratado

,id,nome,data_nascimento,sexo,peso_kg,altura_m,IMC,Idade,faixa etária,classificação
3239,3240,pessoa_4700,1930-06-15,F,71.6,1.63,26.95,96,idoso,sobre peso
624,625,pessoa_4406,1930-06-18,M,90.3,1.60,35.27,96,idoso,obesidade grau II
3906,3907,pessoa_4610,1930-06-25,F,49.6,1.56,20.38,96,idoso,peso normal
1813,1814,pessoa_4336,1930-07-09,F,64.1,1.61,24.73,96,idoso,peso normal
4715,4716,pessoa_4277,1930-07-19,F,53.2,1.49,23.96,96,idoso,peso normal
...,...,...,...,...,...,...,...,...,...,...
2477,2478,pessoa_686,2026-03-29,F,7.2,0.56,22.96,0,criança,peso normal
2653,2654,pessoa_642,2026-04-08,F,11.2,0.47,50.70,0,criança,obesidade grau III
2628,2629,pessoa_820,2026-04-13,M,9.4,0.47,42.55,0,criança,obesidade grau III
3646,3647,pessoa_958,2026-04-15,F,8.5,0.45,41.98,0,criança,obesidade grau III
1419,1420,pessoa_612,2026-04-16,M,5.3,0.45,26.17,0,criança,sobre peso

(i)contagem e o percentual de indivíduos por classificação de IMC dentro de cada faixa etária

/tmp/ipykernel_26355/1848233536.py:62: FutureWarning: The provided callable <built-in function sum> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  df_i['percentual'] = (df_i['quantidade'] / df_i.groupby('faixa etária')['quantidade'].transform(sum)) * 100

   faixa etária       classificação  quantidade  percentual
0   adolescente          baixo peso          85       24.78
1   adolescente    obesidade grau I          16        4.66
2   adolescente         peso normal         198       57.73
3   adolescente          sobre peso          44       12.83
4        adulto          baixo peso         165        5.82
5        adulto    obesidade grau I         281        9.91
6        adulto   obesidade grau II         159        5.61
7        adulto  obesidade grau III          64        2.26
8        adulto         peso normal        1468       51.76
9        adulto          sobre peso         699       24.65
10      criança          baixo peso         481       51.17
11      criança    obesidade grau I          21        2.23
12      criança   obesidade grau II           8        0.85
13      criança  obesidade grau III          26        2.77
14      criança         peso normal         358       38.09
15      criança          sobre peso          46        4.89
16        idoso          baixo peso          34        4.03
17        idoso    obesidade grau I         112       13.29
18        idoso   obesidade grau II          32        3.80
19        idoso  obesidade grau III           5        0.59
20        idoso         peso normal         353       41.87
21        idoso          sobre peso         307       36.42

(ii) o IMC médio, mediano e o desvio-padrão por faixa etária e sexo

  faixa etária sexo  media_IMC  mediana_IMC  desvio_IMC
0  adolescente    F      21.45        20.71        4.12
1  adolescente    M      21.53        21.02        4.14
2       adulto    F      25.09        24.11        5.40
3       adulto    M      25.44        24.02        5.69
4      criança    F      20.11        18.41        6.82
5      criança    M      19.73        18.45        5.50
6        idoso    F      25.76        25.55        4.88
7        idoso    M      26.00        25.62        4.58

uma tabela que destaque os grupos (faixa etária × sexo) com maior proporção de classificações de risco

  faixa etária sexo  percentual de risco
4      criança    F                 64.0
5      criança    M                 60.0
7        idoso    M                 58.0
6        idoso    F                 56.0
2       adulto    F                 49.0
3       adulto    M                 47.0
0  adolescente    F                 43.0
1  adolescente    M                 41.0